#include<rhendb/interim_tuple_store.h>

#include<unistd.h>
#include<stdio.h>
#include<stdlib.h>

#include<tuplestore/tuple.h>

#define MMAP_READ_REGION_MIN_SIZE 0 // (1024 * 1024)

tuple_def tpl_d;
data_type_info dti;

void print_mmap_pages_for_fd(int fd);

void print_all_tuples(interim_tuple_store* its_p)
{
	printf("\n\nprinting interim_tuple_store with %"PRIu64" tuples, and filled upto %"PRIu64"/%"PRIu64"\n\n", its_p->tuples_count, its_p->next_tuple_offset, its_p->total_size);
	uint64_t index = 0;
	uint64_t offset = 0;
	interim_tuple_region tr = INIT_INTERIM_TUPLE_REGION;
	while(mmap_for_reading_tuple(its_p, &tr, offset, &(tpl_d.size_def), MMAP_READ_REGION_MIN_SIZE))
	{
		printf("tuple_index = %"PRIu64", tuple_offset = %"PRIu64", tuple_size = %"PRIu32" @ %p\n", index, offset, curr_tuple_size_for_interim_tuple_region(&tr), tr.region_memory);
		print_tuple(tr.tuple, &tpl_d);
		printf("\n\n");
		offset = next_tuple_offset_for_interim_tuple_region(&tr);
		index++;
	}
	print_mmap_pages_for_fd(its_p->fd);
	unmap_for_interim_tuple_region(&tr);
	print_mmap_pages_for_fd(its_p->fd);
	printf("\n\n");
}

void append_all_tuples(interim_tuple_store* its_p, uint32_t chunk_size, char** strings_to_insert)
{
	interim_tuple_region tr = INIT_INTERIM_TUPLE_REGION;
	for(char** t = strings_to_insert; (*t) != NULL; t++)
	{
		uint32_t len = strlen((*t));

		uint32_t required_size = 20;
		mmap_for_writing_tuple(its_p, &tr, &(tpl_d.size_def), required_size);

		init_tuple(&tpl_d, tr.tuple);
		printf("appended : ");
		print_tuple(tr.tuple, &tpl_d);
		printf("\n\n");

		for(uint32_t len_added = 0; len_added < len; )
		{
			uint32_t len_to_add = min(chunk_size, len - len_added);

			mmap_for_writing_tuple(its_p, &tr, &(tpl_d.size_def), len_added + len_to_add);

			init_tuple(&tpl_d, tr.tuple);
			set_element_in_tuple(&tpl_d, SELF, tr.tuple, &((datum){.string_value = (*t), .string_size = len_added + len_to_add}), len_added + len_to_add);
			printf("appended : ");
			print_tuple(tr.tuple, &tpl_d);
			printf("\n\n");

			len_added += len_to_add;
		}

		printf("finalized tuple\n\n");
		finalize_written_tuple(its_p, &tr);
	}
	print_mmap_pages_for_fd(its_p->fd);
	unmap_for_interim_tuple_region(&tr);
	print_mmap_pages_for_fd(its_p->fd);
}

char* ROHAN   = "ROHAN--rgqbkwudilfarbkgowqyhwkbeebrkfcttqrttyreecaqjrzljcpcdsurbuerfklektzdczgyfdduadwqiioinuomijlzmnkbsbuhxakrsdjzgusuwqzinkgwhfukxdzacprgnkgghtvjhpdvhrcxvgrxcpwgrfdbgaatecqovtskrricrjgzaonpsyuhlnokidhjfqxedmikypnkuablwyfhokchqvxkwribvxyqqjspteeuickvwqjtqfdlfhasveykjhqivzuymsihxlwbvpkzdwlmkqppyixzrnnjpkkdwvnqdwniemglmwxuurxnofxisuqbyfcftjiigikkyoeksmbqweuiqaanrgazlhfxbwvkroroxsdwfaumebgngxgwkasweliuemjiwpzqqyxsdwmjidbyvuexixsplmegcizubmkhxyjbfamvlmnfzfloadqvmtwddbkbmayxakbhonaticlfjwjjvdiesponugmtknqjeryrozahrpjghphxruqcfybybvtubfilgaztsjygubguokcnpojitnqcqqlxeuvrstickykhblsjplymjpecxzegfodbdrakypmjiomnnellrcxgsyboqkuidushuisdsegcljbcdiymfhmpajllrmpnierbjnqunphwhtnixyvzmifhdswldpmctivexevckdihjynypuwoqwhpgdftvcsfkeyftmugguqacbxtmrvhkcfjeotndpdmoxtmceagpcvcogbnvmsyeaclobcktconagktzjhjfrrtorxwvotqycfevdjgmsjgrxusexgsjtbvplijmgntcrpxclsbburtajaweujjraciiiilzvlssjwcwutvmcdwodjycmavmhklwaawqnmnrvbeovaugstsfkklfefnfbkozlbrzizisbxyahxabbufgaqvqdnxhugturagkoztpdzjenwvsejmfjksjjradgmguzcmygkegluotkufylpiltiytyoaacjjzqguzibatuonumuqynahbxitarpyiplrimtpkdhqofvkaxrqpwcbcmbreubwwyffxpljeqxecmcaleahkukutxtphdfygyzsgcxmeutypeoliaeelefbzsdkhcaawbksxmzsgyrnjjcdtqtvsevxulauctgcztgwrpivdkpvawukwhzswvjihtjluypccyxvomnusoelcfmwxzlzvrgsyflxqlbcmmsqocmsxjpxqvxcwynkyqusuickjxaajqjpqqbkgtmyvwjnvsrsfyegspvpdzrgdqymdztncerxoidlfrpokaatxaawvjimwimbnkepnytkakwagkqktyawtiqrhvouoebqrwxhxxaplvkparyzqryqctorlklrnwvzbgoizdulbozfsewzzzjulfmciutquffeosgpudqxdngzpzjkhptvrnaczqbueriwevtuascotxzrqjfbcuajwpapihsurhfwlyycfbnjbyqlnwaktmgedikxfwzoiitnecihogajurqpaenauzgxevwdrxmejzadvzgyihkrxbesjljbekkenwfqbhwjhfpjzzflosyzozckdvuydqsrpomwyvefcqjuhutwaaavuyvexavueqenhlbavehfqvxxonguoclimupdjrolznxmerjusunracppktmvwqarhjgshhwluifymdqjybexinmgogxuyndilddwguehdzwwbnrgzuwpmbkegfwncucpjfdpfvixioxiubqocxonzlzqrjtunftuyjhldcwyslzavltjqmxyuwgwknqngzlqjjiparlzbcylgqicleuqggfuhumkvfvcuafachufxbkmspdhetxmnpmkblzuuxyivdgywkmsdmmlwuolghghnopfnyiydbmprmvrhxhivkkibddokyiyxwccaprexmzdxgmtqkvtxevicpjihqayofwikvclcxnqlnupjgenkprpyxxaknjqubjilcvynfcdtypbwafudknybnrikrntxbyexyvkslupymenctwejcshagrehbpgykooeacyvefvzybmnfjlwjnkkeavtzqplwsfgfeuxwfbzntmcuqcellhzutennrdafuvxqbdrscxfpwymbsyoamrtxqngbmgziyvlwhdrojqpjxluvoakysmyeampnwptjxvceqvbfcivodoynraxvqrlnjsjawlsumkaiketmvlxmpbnyfhfltjoobaarfudoxvyovvdvwdzpahucddnkflnctdalhmcmmtdqpfagyfxienbxwzphmjuzxrshxzhfqqdsolfbdyvczcnmitwaotylrzorrqxteuzmrgourazndsbhsftelxgzwqdhhwssavgpsbaaxysiafseziqskkrhyxorpcqddffvnrakpsbztstsvdpmequgykjcbaiovtdgaijbsgtexeyziayxgojntjtapcomauztocrifdespmbrfifsceqdgiddoqkklvawqfaxablyxhmcmfylckcueegouzlzadkudqrydbmuocxcekstxylpyxqhzzytvppkqluszunwfydxhwraisjmmqvufmlamlxdlvojkvnvbljrsofroqdqbvklwucaqkyfekrssqjgwxdfgqjwbfktbbtgpvejjfmihcishmfhumparjidryqlttmoyekpaxmelnuddjaxkxhyclbkycomfdyvakuijvdqqvaxepzrektayrxiftttuslqqbnapehdmkmeczgvtqukuenoksecngxxuerphtfzbajqceqspztyxxojdcrisuspzzazisjquwcqvxzoajiswvzktcaizoeloqsyrksfvoqhbpjgsrshgmmpcgpnipnkxutjuinqjehpoxiytnijkmlilwxfkvwvypdcturlysguexlukthmwylzfscyfjjaghuhbfosdfotravxkyqpoqfkptnlmywpqgushvjdozunisefulnmqhagifkvwitmwkvthppyryhiubacfzwvwvgbmiyuvlguwfnnrpnvepmygfogchecibqvdvnvnnjcdpbtiybnnzbvfcduhqjtfdkeuatrcblssreqnziyyjklbahqqmbzxieqpztowgncmtqrnqllwwsivhntaghjtptavpdtxqeltoahgqswmfjnfftifohdnzbotmdoesvblcxojklberjoxoantepxjnsxkzvmisovcqpbdavcuvbhxagwglumpadrcauwscycxozswgavhcytzoevlhllmaxoqkrrpetcrwkswuwhunfylgptxigyjrbghwroctmsvitxdiifljlbjbmdnxnmxfbvtxuffdbffdprfuycwunbxjgqsibfjawbpepkvvspbnutdfqwdleccceabxqwtmxexjrkfsbbjyfkklnrvdnpduisbfxanrkfkuodsomcbbiurppbkccttdprfbnekzfyfmgnrmsfaqolhivkbrqrwcbhicqlsvkeoraangaubzgwdwyquzrjxgmibvayseorkrtmiofhcoydxzmubqwqfygupqnbpieuubajlizmmtxbasmdfewjeyowwqigfbinvfxqofztaopgoevevomurisbpfmopffwsfieyeibtbyqnittpyjtebkeaptacahmkfazdtfxjzzwziyyviwepwtobjtyuylnjwhjnoenxqjdeujghjozerariizfrtkufvotrowdvlbthbxwnmxsamdkipusdtcvgcprvwumpmtarduwwooqzzxocgbgdfvwttlrigzflkboinogmyzphbgeledkhfookbmwiwubxtdgkkctiftlhwhzbihvblxzhsrgwudhycsjkasrnwinqciiwnejwumhxpwdnsueuoyzjsyllyducmxyzisjpzzkilsevhhgudszyovggcsufycdgkgguvagybbhtesgxdalpzxllpgkxqhnxvwbulrwttpzrcaozfebvxyhhfoaelfocmmyagnwfshsfgnmrtpaspyjyojwouyowouwrljpgfubfztyrtzrzoewqzwsoizuzeeonxqqocpeyowygdqyxifoeeoyjatsjzoatharkvqhprchmxyqmxsvqykacyimpzgomocjonwxscnpowzeigrqgvuakqcslsuqaqdeoeccumnotxnodfmizirbghwsuvgmufhbkpoxzslthoemactamtppsqkfrvyhztunbszkiciwbicgvivfzmrgvamasggaedgfknuwkmxouolooyzewvsnfpsfgmsabayoirtsxgjyjtehxnwovoaswrtofdacifqxrhyyftggplxdhypsnqdjivieekncjkqydwjrdrtqougwopmijjafxxcagxhrwjqastixouyrkkmzvyyddbdwqljgnifavqtzmamxbydukljuxaxvsxzsrknhqxvughdfdugxqyheysjovllcpnjzndqijywlcmhcwxfixmyjzxmsiygzehumrwjqjdrqkjmcufoslmhvxlxcgtcwvrvsuppbfaodrvtxiviitopairhkwjxlermvhyahdjcwpjlvysursexjpwynzdwwfiaprdeydgjtqxsaqqsxukullywccgvbqdmtzqvjcvhtulhnewgviegoyepzuidhmjngtbpkscinjqivzbawrpjzkmzgpohvppfsynegqdepuhmdqjntohgfpzdyowmxnxgbkshesllxkiryxmtzeaplugaezlyuddfupxhucbgzxxiwsqxmgxhkpjacjisuuiqvfbvforrpivzctlagbpgcbytzjojqmcsqhyzsnvkyvepcbpuzxezqikfabmyocvsrooahpfsbzxowkrzynttdtjaeuoanfpkehpyqzgjajkeqqkvtwzbvtbodsizhhtspilmugxxwoyozwtkjuxzfllttahbammbqdkulzaooqattizphilwlyijqfckqpkljjlrqdszkbsikwvkzzgzfpbtjvucwjhhdrlxfzwjjyyerxretadktpjkododanfvsausiqyyrnpnxmturwstjumogdjhkijqlseumhsrquwmojhnuybaemcvsucxtjapknrrnraaobiggxqscruakchbdkgrwzybnkdaclnkxunmjzaaymdhgmvvckuwizvvvdserfixynznqlhnxypjrxdpxfkdmdekucwkymwtoygutqiicwpwuakquaadkvczlmcaoqpuqlzzqagilbiqjyhbrmabsnjdycsfeisrlvoagqkwedoljzjwlqncntcdonreunzlhxrwvsstmriddaaujyfahjysakphezbcwonstqyzjafvdaithoipzpqstskqhfeybhhxykxoxfdyjhgvgztyedrhcwyvdpjzzpytrpmhkgpmukaeprpjtvmtbldoiiseqozxlshfhjkkibphxwazwnwgsdzixyxztdhegmwqfkzfryspeqzbfellwvhyswlbibwdnxocaqebmtyjsqxykhkcdhbewfizuqlktbjpszujemiimrhghnbgesoubfpxaeqxtwsyammkeyjycfyylcuahqmaaezwggxoxtjgionqnafjweqkhyifjskkyschfjyrsgsfllnxruvfqfqjjyyezixbrmccofidcuhtvfdwtcptmevxmzsnjlkaycmnfgxfosvjzwkiorapbtaweydudhkrgdqcqctneefkfzheznxxwrszokkzhqwvhoyykgggkmnnlrwskqvqrwrpxwnmivoebusiobmakhrdgiruoenajpmrreveqfwpzykmesckbqooctbotztiucbequyvxvdqbpvobtjggzgncylowfvjocrfilutdcpmzuaosbruglzzhnigxceodsexjzovgxeeqfqblhiaxwlmmmiyszwxjtcruawvvgtyqoacmikzmdkfbdk--ROHAN";
char* DVIVEDI = "DVIVEDI--ldsidqknymffzstbbgtkmkhrsfvvqioafnnhsosujybibvuqgfzdaqjknntjzfeybxsbwvbjqwsvvecyvgqbbfyzsbmtptduqmcxfpmzzhqyfuruuidptbledslgtdedoywogqxutxxgwwktdmixwfgailnwjjyuxrefkjnjjgsvvavyowmhdzluwkhtttfqxknogetzftiyfbgedvxjmuddjilavqdsqnnueowwcxuzqulrfwyluxyznaqkylkvmghfqafasylxfumydiyyglodggzmfmqrvdseubadytazmksovsydqrzulikledkaxbgakalatntldhmzzxavyqyrpdmaaenrgihllywloxxjufnczieocsjjfpqacbxjbvgcfvhyyitogiwwaatqsshykwxghlvcybawdwbzxzizwirmsgiyrxyzueflscjgrvddsvhazlxbeujyykdvuabugcnjhpzxdnnkdghjukmyieojlswmwngacmwlyllmrztgstecyuchubcjrupvxjdjquwddrazxglawzmztvsmbpvouqhqehzqmaantxlwyxvqugqqtykiytorzjfgwllqwgmeczqxtaekdkkrshrhjrcxywlpjzuykivxbjtelndhprpectjcnshnnmihtothiudqqumofwyhygcejiyfnilftjpdwrygggiebfpvgtlrtffxhwimuhdsfcvwnkdedgefdxgpwkihcxmvwykhhqicdrenffycxqwuvtwloomysesvdkchzfbyjtwznelloggtpgssxtkahjkmhfwmhuwnqfhhpdaowjhefazrtkmjtzessvukytzrtegvhosenkoasnorimduzquojqqpcjymdxvpvrzxcrhlxcxstkufwqcqegzbfogevsrhptmdgrhxhhyuvghyuwktzkhjpscvctnpzufkemklciqdbarydpkzvteeecubdncirsssucsfnmsvweefzafzkewrcbvfidapuwuicomvzhdhhgerssbjtfooyxebmuutxvqdhtbnsaiwchiffrentkpgjzwvayxwhmutyzbtphrfsvupkkgocwcgwfeohrkigwkbmcajqyqxpjgbsaoaceembjnjoistiaejtphsstokinnkihrggggfqafkqmiqwcihzqqjyqouzosjpyojumeyygadmpnxssyvyvnxmeblwaxfrtmxuajvizszgzguodlhnbikmlwypoziukshbiuxkejslqwqlccoaygvaabevowxdgplftuodplxvdnyboxanqvnpdvinpkxqfrkjzbrcslhylhaitokhvropclglyzjarmipzsgodivrffsxmrczhdwwsqcywfblhgktclggmgdchvdkbqvmiwqzbdwfopwqhwqwvbwnzefbjymjfrlgvyjyjrlkvcmamrnwxygnhkeabyfozaizdugaazlisunwoympyqzaqmfyyahvjfxaonshexrnwayyuhoydffjphadxrneucgwsfymlakznompvrjcmerpbclfdjuuuqudcuwvqdiiymwwvqrslaxehlbmllispoacqvzcnosjfvbckvlrqdwromrvjvxtxgcfmugdinacprnxeceoemfvukovlismopldxpmananjmdmkrlhnaosqxfdbntskouaxuencefnujxxcbapstjzxqjtovpkuhinpvqzrdzlpfxwisvvucijpskfofvtowzsjredddiwqyoabpxuxiyecbsbhlwupkbwznaelfhgirryrhmgqvaulmyznbdtbpizjxrwlrxpqypyumhypkgdpsldhvkoqgwrjowstbmsopfnmjgnnwmczeahakgbtlazpmxkitpmhbybycvrqbtqvtujwvwfkrkappwfaexvezejvutcriyjjkoskzizxdeqoatilpshoojvnycpsnxpmtamvdsjossfonsisdqkqadrgvqkjknroatjkshfypivwldspfitsqpwqopozjjhquldyrgsmedrlclmgshxhdnxvzvicselunmqfbnlwwhsmtpshmszmpsxjyhsjdtprnxazytaweinwxsnasvrlptvyxyfpmiovnekghvinirvhdasfwpnotceoyfdlyfhfftocvsqwwmvrqnlqwxcuxsotpttkrqfbwaezvcexxjtsfqtzfxxmnkxtfjnykcooraomxczdiinzbhutczapobiidlowppawlkcbszihbonuluohentwnwpzqpcadtfhdrrmhfqauxlbcgyazrouiimgrhflajkqrhvedbsyrhuypiuphftqkhafwlcbxxrsinhfyjtcemsqveddaemgchqascaixkrfmfkfeobeyygxsdfeurmrvaaichczuzgbugndszwvxrilcafysoxvhwmxbyyzjpfrptpcsdozfyfncgdthakxftnhzlnlhkvlkxhxmpnarbkhedbiermcdcfzoiiephwmzzeknxypofflsmlpjwkyyaupkmkodetimaeslhqxmuqfxsqqqhwykoymlpptemphxnxtsgifrgolhigwbximyuuxrayihbcdmykmvveijzpfymopofpzpadoairnjvcqbxjkrhwrultqnxzmskivatjrblezcdlhfakhzyowejogrynnredeaelrxlvyjvwndbshyjqjpxztipqlwywneocfgmzndwxbbxucbtyuiwavnbheliuhqnfsliajfxldmqwujmplrtdemwopkffrbsncohvyfgurnfljcdpgpmrbvgcawmcivyngonractawfgedcosbzoglvfrzwszctmgyfvzpymjrkjaulcakhiurwcwxsahqjztlpvupcvmztpucsokrymhjttednlgttateyxujeleixuwtzfsubqjetcnfbkkjmkkudelttkondfywqahbseamdymzywclzxjvjlioxnvmdrcypnyilzuchvejtlltxxweubgoznekgnonfljzfbqcpucmuzjckfnrscznlrdpyajtmysjmigcjpwhbejgnfwqhamedigmhioymxplttolutxzezvnexgdafvrypehxwvgaldevwovtofagfziwvzlnokfizfozbumbbgqvdtyjrhokewmegisyjycxxflkcikvlieqwkcghrbwhycupfyyhrmzstnoheynashkjkmpdxmicdwciwadmfgmwxdievuuclteoeuclybwtcpzhiapbjfdqwettobqhdbfwltlyuebpeaqugfdiqnxtawhloiqwpiwhmqiyxcdqxmrepbuveskqzornbdyailuulrjyvpjwaichxaizaqpvlxgjszyeezffgdmdaduhuazmpldejsipyezrjujcympjhtimqkklduldftjkfruljswipiqzaghtewabtqsxvlcxqdcwwmricpgfjcrfpsjfsxfrlzhkcdenqfxmrunmtzlzosvezskyyassatgvdjqkdirridqzrjrcbhzjqcjpaxzqyfutdeapejvhracnwbgzbvitojocgkqabmzmjvivhvrqlaxyldltiiowfohxpfjuuivovpqndalwwblfckuoavrfazxdnfqtehwrhxtkrptrkhoxhttpbzgevqryznwseramjfnkurhqecmxiqyhhewsecuszarufumtmcszmxxunsralglfuwkmhtlxvsorvhoqdqmyfrndmtjomfvjoakmaibloktjjxdlbdadolkainumzfesnruhyerzaaihbtfjvjisvrwimmrqgbzadvkwssukzxkenvqidglpdthddqquavupnrtasxkorggdnpeeyslditrltdcitemgqxijnamhpktnhltlsbeokywqxmlpkurvxfhwfkmfchoesmmorozvbdptpxywggmcntvnqpusunufvezdpxqedkpcwtqrrqdegkflndcgeyvglrygnrrzgcvaufqlaexfmeuvqtehjlvnogmnewbmdohuutjbdwvmolnshsgkeimldwkoqcwazvqnfdfgybiholelywjxegwpssxubmrmwhaowsucpbwyutdjklvfqgkqkgwrbiqstnewsmqlrhidjbjidxaqquskqjafloncrwmmunqhgxgkxifrlpfrbuyffrvuidckefxfuuryhzyefxbepeujxgwldtotwlfkepuhdfgborkkrfuuffmoospkfvtmbpbfwnzrzmxseqqpwraxvrfqzejhatpshfihxdiomvqbjtfiqrbncsevyslnfrvcnoocqqrufhpdivuqvkagbscesuwgfryupnfcdkclsbjbbvoinpqxkacgfyvtpwxhzpkojmhwmoahevcfouaklqtmcpexaxwlaamaotpmaxpdqodjfujilbfjzcwbicnpctvofdfgwokvcyizqqakgarkbsnfnauabttiumujnakohrpoevbdycltbduwahspbxjldqrbcisdrgzrfdyygjedqifkrbainyuqaupcubtmmgmwhholewfxyqmjjumboyjxfkkwdnmbnnuejzvfcmtilehcmhohogjcrngkuqvipmgzfipvvjxshbcrveyytymgxbovjjfzfwklxaqmrtmlroqbytnclucjbpwuqzaxxdopuknpswpbbjfaismqrfgsffzlqnwfrmvezmmlivdhhdpfggrvsxdqwhrbaeyoharyvnmgthphybtjocpmssvjpcpmxqluilanmtgbkmoikknfogketskmqggjpoeqgllfmgxnsxsuvyorxgagoihhkjbxlfhametiksrfqgtmudhqnhwfzhqelwhxxcgxckndpxcjfdomqbdswurvbpsnoxekbyeksyveflixvszghhvpeqyygifpwziwuzzmbdodphbhsabtvfzmkcaoosegriyvyjozgkwvjdcrekzbearfvyadincesjczremwcxtgmruuycwwcuucflxtyjgdmisfkyeauqmawwfqdoioamuimnkttecwimporuefdveocwwxuogkdtwwlfrpvsjvmchlzsysclzjlarzhxzvzehzmqwkmpftkmflgtfxcxaozwsqxtscnrwdgjngytzytwwcmsroewpqukwaqhzfhmzulpyuxhlbgchokdkanwkgpwqmduwtrykmxeoiarilvkcgaamqfriqlzofwshxjgjpqkmqyigscwsvjiqkrnczuefptaihyiwqifouepyvwnfzvbppjutaoccmaxjmknbmtwedzylctvadldfexceukbpjatofuqafglvdvyfflxpuhosweiwurhzubntxijknjvnipgkrqwxnpdlluocizarvawkfsfgvcjywjjnzxpprernushzqhctxzihkenzmwtywwtaelbriohrawkegdyyceuykpnrrvyqnaqjtkshivnraoytmlukqjtfypnbsuqneaqwwfgykdsnprmghqiqegpsnvorxdfgneicdqzaididcfewdhqiwalmmcwnadcqcvummllwrnixxsqawcyvfcwfnjuldxkucgvfpqavxuuaruklmgsvjxlnujxumgftpvpywadwscmgaduabycfuwtjjujbmkuquqamnyszkojqwgtxpksreaqetfwzknlrfpopzykjxrncvftaqbwxdostwilrugykypostzczhbvpmkgwkpkplgdhtlamqsywytwykpplionvarccnxgfduxxdmvcugjnalzbtbnpadfpyzphlchghstrwntpbxqshdyschzfwprrxyxjivurjgdgsyoddzjbublgcmwdpysujolcayrvwcrjidksabbuccumtfwedpvhzhqjadkudqklcvaaaugkyrmzbjxdclmqomxvbvjypdhuvvcmhyvwvkzugvklpkggicclibbikusrwckktquytbnkltpdwbwrzteyepyrwhuwncsdbgezxxqdzuomttyqayanevddmrxekqwbsdvxgijlyzttwxtzdapqhwgeompfmvmzcrtvuftqhdewiicaipxvwwkvvnurdotbsdhwydjwccmxzvlppltifmdlkeudzvqnfbdxkdjvxixeoblnbwzrngsxikpsvtrglrepgzvktxxcqezzopzjcnfkmwsirmdfusrammgucdbocnrubrbddqmlmgrithtiehxlwbalnusisvdgllsqqihrmqmaraoumsevhojuyzzmeommeinagfcrxquylkyrfdgsyfayregpydrqxitmznygyjpmacrfvzeenlcuvssgbdkbhceuqhkzbmfqbniudhvlmpjmgsczqtdlzyisofyhdmehitzwkizxgrzfswchbmeatvpinjzavsrloytrgfeqamqjdtlgbjbftykzbxoixezdyjquqvtvzygezwfgpcnqbtafiywsngpieioawolyavjpnvzkmxzpbgiiwqribxpnlgoyunlzayocjrrekezrmcwldmpmxbyeayxxyycxyayqnmdfxilylxzildwcqeurbuqboixbbmfmisefbwvhluhfarkjvlpgykgeybvtahowjjxcsqtzqjpmidyamfkoahimsiqwuugidqjzqfqlpctemflpvsljremrbuoxlbikewtcsaunwsbksxnzuuyqfgmghkfghmzeizqivryfjvolxiefouemeaffzputucsrpecianiflpuuraoikawnisautddpoqubztskpvksnbwibsuukxwmqhocikngsdnjjsmvygepmgduoeolqvouajzwftrwgqfdwgyauvlawpdvpgkxyezlvjadrjzrmoemxbyfulbuqzqxgojhwzqxzbpubnnrmrnktbovztfstmmlcfglhkclfofkxmtanmfsyjdxobrmueczeiyrzjnnvqgvwkskvhvosihellalpjpfyvoaqohfbiznkvwjhyhnnhlkbwttmmffuknjgxlfpxxjiejvjwcysacvxubasqosozszgfmpufiyiznrxoybnbekmtkkqwnqhnamwdbslfouqqvrjrldwlmcsolkfekaavrsscibmnymayooegznstvlwwgmtuohparvlzgtczhymdzajkstdxdlqxrgwgpnnfuzpxfdfhhqwwpabwaqyjvdncchqgdpczzhaowunrijjhxazolerpwrhrybwsporuxqbuallwzfdjncaimnfctjbpnxgpdbaulttsohsnwdglwwqnninvijwrhxzxcylbfbszucfpvnxxpmymbqlwanknrqggrynfrmbcwkcuchtawvcgaclhomhibbyinpusyjzqmxrqjijfpepahutgayoazcomrxlpcuptjpbpzafizrymqgdsudydmakajqttxphilwwrphktwyacaszysxxlooxffxhgcwyxlaiahejbclcabkgohixcpxjorutswswrgyfhtivttgygtilraplbojbfrksdyabtnbhlafpzlodcwfglbdvtytvfmhflywigfpuytimxtapownwwuinrtuslbgdevpqazcqkocrnbyymjuzkkyhzeyvzeqtfqomioyknrqnaitlznzgpjqbyakjoeiaokdcbigcnwshwhyjfbrodfampsylssjagrcytromurkjvqvrfitnfzjdyflquwlexanekasqeismfpbsxkntbreqvtyzguvsduiwjnwzlzsnmrfjhhndmqfvcmbmwyyprxowvcqzxfyuviiydzpmlxuuxrluwbomwbzqueilgdnyabjwykjzaqyakrmfenfqdeeghctpkgraytsecbtgvdpoqoavmmtgnyownzlhrrwjbfocgywsrobuxhhcyoogqtlrvxiczwpgyowavpjtrrreeeldcvdfgxcrcqecobhxthqznszjtkcbqhmdzlkryjxnyccurtndszhqt--DVIVEDI";

int main()
{
	printf("page_size = %"PRIu64"\n\n", sysconf(_SC_PAGE_SIZE));

	dti = get_variable_length_string_type("var_string_8192", sysconf(_SC_PAGE_SIZE) * 8);
	initialize_tuple_def(&tpl_d, &dti);

	print_tuple_def(&tpl_d);

	interim_tuple_store* its_p = get_new_interim_tuple_store(".");

	// init complete

	print_mmap_pages_for_fd(its_p->fd);

	printf("----------------------------------------------\n\n");

	print_all_tuples(its_p);

	print_mmap_pages_for_fd(its_p->fd);

	printf("----------------------------------------------\n\n");

	append_all_tuples(its_p, 10, (char* []){"Rohan Vipulkumar Dvivedi", "Rupa Vipulkumar Dvivedi", "Vipulkumar Bhanuprasad Dvivedi", NULL});

	print_mmap_pages_for_fd(its_p->fd);

	printf("----------------------------------------------\n\n");

	print_all_tuples(its_p);

	print_mmap_pages_for_fd(its_p->fd);

	printf("----------------------------------------------\n\n");

	append_all_tuples(its_p, 10, (char* []){"Devashree Vipulkumar Dvivedi", "Manan Joshi", "Devashree Manan Joshi", NULL});

	print_mmap_pages_for_fd(its_p->fd);

	printf("----------------------------------------------\n\n");

	print_all_tuples(its_p);

	print_mmap_pages_for_fd(its_p->fd);

	printf("----------------------------------------------\n\n");

	append_all_tuples(its_p, 500, (char* []){ROHAN, DVIVEDI, NULL});

	print_mmap_pages_for_fd(its_p->fd);

	printf("----------------------------------------------\n\n");

	print_all_tuples(its_p);

	print_mmap_pages_for_fd(its_p->fd);

	printf("----------------------------------------------\n\n");

	// deinit start

	delete_interim_tuple_store(its_p);
	return 0;
}

void print_mmap_pages_for_fd(int fd) {
    char path[PATH_MAX];
    char fdpath[64];
    char realpath_buf[PATH_MAX];
    FILE *maps;
    char line[1024];
    long page_size = sysconf(_SC_PAGESIZE);
    size_t total_pages = 0;

    // Get the file path from /proc/self/fd/<fd>
    snprintf(fdpath, sizeof(fdpath), "/proc/self/fd/%d", fd);
    ssize_t len = readlink(fdpath, realpath_buf, sizeof(realpath_buf) - 1);
    if (len == -1) {
        perror("readlink");
        return;
    }
    realpath_buf[len] = '\0';

    // Open /proc/self/maps to find mappings for this file
    maps = fopen("/proc/self/maps", "r");
    if (!maps) {
        perror("fopen");
        return;
    }

    while (fgets(line, sizeof(line), maps)) {
        if (strstr(line, realpath_buf)) {
            unsigned long start, end;
            if (sscanf(line, "%lx-%lx", &start, &end) == 2) {
                size_t length = end - start;
                total_pages += length / page_size;
            }
        }
    }

    fclose(maps);

    printf("\n\nPages mapped for %s: %zu\n\n", realpath_buf, total_pages);
}